In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:
data = {
    'Experience': [1, 2, 3, 4, 5, 6],
    'Salary': [45, 50, 60, 80, 110, 150]
}
df = pd.DataFrame(data)
df

,Experience,Salary
0,1,45
1,2,50
2,3,60
3,4,80
4,5,110
5,6,150


In [4]:
X=df[['Experience']]
Y=df['Salary']

In [5]:
poly=PolynomialFeatures(degree=2)
X_poly=poly.fit_transform(X)
X_poly

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.],
       [ 1.,  5., 25.],
       [ 1.,  6., 36.]])

In [6]:
model=LinearRegression()
model.fit(X_poly,Y)


LinearRegression()

In [8]:
experience=poly.transform([[7]])
prediction=model.predict(experience)
prediction

/opt/conda/envs/anaconda-2022.05-py39/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


array([197.5])

In [10]:
# model.intercept_
model.coef_


array([  0.        , -11.16071429,   4.55357143])